Mentions
EyeSeeTea/d2-analysis pull request #18
Opened 2018-01-29 15:25 UTC by adrianq

2018-01-29 18:28 UTC, adrianq commented
Closes EyeSeeTea/dhis2-core#18

2018-01-31 14:06 UTC, tokland requested changes
Some general comments apart from code specifics:

 (using AT to avoid mentioning github users)

- Autocomplete is not implemented in the "Write Interpretation" popup.
- Visual: 1) Start writing a comment, 2) Write "[AT]andr", selector with users appear, 3) Click "Clear interpretation". Problem: The selector dialog is not hidden.
- Visual: Write "Hello [AT]android". Now go back with the cursor, when you get to "Hello", the dialog re-appears. It cannot be closed other than selecting the user already mentionded. It does not allow to write a user mention at this point.

2018-01-31 14:06 UTC, tokland commented on src/manager/AppManager.js
> +                previousResponse.interpretations.map( interpretation =>
map is used to collect results: `xsDoubled = [1, 2, 3].map(x => 2*x)`. To perform side-effects within a loop, it's more declarative forEach: `[1, 2, 3].forEach(n => console.log(n))`

2018-01-31 14:06 UTC, tokland commented on src/manager/AppManager.js
> +                         if (mention.username in mentionsUser){
This saves some lines: `mentionsUser[mention.username] = (mentionsUser[mention.username] || 0) + 1;`

2018-01-31 14:06 UTC, tokland commented on src/manager/AppManager.js
> +                mentionsUser = Object.keys(mentionsUser).sort( function(a,b) {
It's a bit confusing to reuse the same variable to hold different values. First `mentionUser` is an object, then it's an array of sorted usernames.

2018-01-31 14:06 UTC, tokland commented on src/manager/AppManager.js
> +                t.mostMentionedUsers = mentionsUser.map(username => {
Here it's probably not a problem, we don't have so many users or mentions, but loop within a loop has quadratic behaviour. Tipically you would build an intermediate structure so the operations within the loop are O(1) and the total is a lineal O(n). Something like this (untested):

```
var usersByUsername = {};
t.users.forEach(user => usersByUsername[user.userCredentials.username] = user);
t.mostMentionedUsers = mentionsUser.map(username => usersByUsername[username]);
```
You can create `usersByUsername` is a single line using a `reduce`, but  it's very cryptic, I would not do it. Underscore/lodash have methods (i.e fromPairs()) to make this task very simple.

2018-01-31 14:06 UTC, tokland commented on src/ui/EastRegion.js
> +                    return {
Code repeated two times, maybe abstracted in a function?

2018-01-31 14:06 UTC, tokland commented on src/ui/EastRegion.js
> +            if (potentialMostMentionedUsers != null && potentialMostMentionedUsers.length > 0){
`if (potentialMostMentionedUsers != null` In the general case it's better to check simply that is "truthy", like you do in Python: `if (potentialMostMentionedUsers`. This way it covers also `undefined`.

2018-02-01 10:31 UTC, adrianq commented
Re the general comments, I have extracted mentionPanel as a module, MentionToolbar, so it can be instantiated both from the EastPanel and the InterpretationWindow. It took some time but it looks much better now.
I am also using the cursor position in the text area. Before this we always consider the cursor to be at the end of the text and this creates some problems as you noticed.
Finally, I have added some event listeners. These listeners handle any click outside the MentionToolbar. If there is a click anywhere we close the mentiontoolbar (I have tried to mimic the Slack approach as much as possible).

2018-02-01 10:31 UTC, adrianq commented on src/manager/AppManager.js
> +                previousResponse.interpretations.map( interpretation =>
Done!

2018-02-01 10:31 UTC, adrianq commented on src/manager/AppManager.js
> +                         if (mention.username in mentionsUser){
Much better yep. Changed it!

2018-02-01 10:32 UTC, adrianq commented on src/manager/AppManager.js
> +                mentionsUser = Object.keys(mentionsUser).sort( function(a,b) {
I am now using two different names... TBH I am very bad with naming

2018-02-01 10:33 UTC, adrianq commented on src/manager/AppManager.js
> +                t.mostMentionedUsers = mentionsUser.map(username => {
You code was not tested but it works like a charm :) I am also improved a bit the comments

2018-02-01 10:33 UTC, adrianq commented on src/ui/EastRegion.js
> +                    return {
Extracted as a function. Note this is now part of the module MentionToolbar as it is used by EastRegion and InterpretationWindow

2018-02-01 10:34 UTC, adrianq commented on src/ui/EastRegion.js
> +            if (potentialMostMentionedUsers != null && potentialMostMentionedUsers.length > 0){
Done!

2018-02-01 11:55 UTC, closed without merging